### ISSUE TITLE
Doesn't work with Non-Angular2 projects

### ISSUE THREAD

**Issue by zweimal** [lfabreges/nativescript-localize#1]
Assuming Angular2 is always use is wrong.
I hacked it to ignore angular files, but it should be optional.

**Comment by lfabreges** [comment]
This should work now, thank you for the report

**Comment by zweimal** [comment]
Warning is still there
```
+-- UNMET PEER DEPENDENCY @angular/core@^2.3.1
`-- nativescript-localize@1.9.1

npm WARN nativescript-localize@1.9.1 requires a peer of @angular/core@^2.3.1 but none was installed.
```
But it is working anyway.
Thanks, buddy!

BTW I am using NS 2.5.0, TS 2.1.5, Node 7.2.0 on Windows 10
