### ISSUE TITLE
How to switch language without reinstall the app?

### ISSUE THREAD

**Issue by OPADA-Eng** [lfabreges/nativescript-localize#10]
Hi, thanks for the plugin.
I'm wondering how to change the  app default language or the current language without reinstalling it ?
and I noticed the app does not take the default language  I specified.
Thanks

**Comment by lfabreges** [comment]
Hi, I don't think that's possible. The default language is defined on ios for example by the user settings, of the preferred language is not found, then it fallback on the development language of the application and that is what is configured using this plugin. 

When developing, you may need to delete the app on the simulator or device and delete the platforms directory to endure a fresh build.
