### ISSUE TITLE
Webpack using --uglify fails

### ISSUE THREAD

**Issue by Svettis2k** [lfabreges/nativescript-localize#13]
When attempting to use webpack with uglify the process fails giving this message:

> ERROR in vendor.js from UglifyJs
> Unexpected token: operator (>) [vendor.js:82349,55]

This refers to the following line:
``` javascript
return string.replace(new RegExp(“(” + find.map(i => i.replace(/[.?*+^$[\]\\(){}|-]/g, “\\$&“)).join(“|”) + “)”, “g”), match => replace[find.indexOf(match)]);
```
The problem is that the default UglifyJsPlugin of nativescript-dev-webpack does not support the => notation, as it does not support ES6. This [issue](https://github.com/NathanaelA/nativescript-localstorage/issues/10) explains the problem. I was able to solve it simply by replacing the => with function() {} in resource.common.js.

``` javascript
return string.replace(new RegExp(“(” + find.map(function (i) { return i.replace(/[.?*+^$[\]\\(){}|-]/g, “\\$&“) }).join(“|”) + “)”, “g”), function (match) { return replace[find.indexOf(match)] });
```

**Comment by lfabreges** [comment]
Should be fixed in 2.0.3

**Comment by lfabreges** [comment]
Actually it will probably not work, I'm on it right now

**Comment by lfabreges** [comment]
Should be ok now
