### ISSUE TITLE
Text not updating when modifying en.default.json

### ISSUE THREAD

**Issue by adil-boukdair** [lfabreges/nativescript-localize#15]
Hello, 

I have noticed that when modifying en.default.json text the modification does'nt apply to the UI after when tns refesh the app, the before-prepare and after-prepare hooks are firing correctly.

To get the updated text i have to run tns platform clean android then run tns run android.

**Executing before-prepare hook from G:\Users\Adil\Documents\Projects\FCash\front-end\fcash-app\hooks\before-prepare\nativescript-dev-android-snapshot.js
Executing before-prepare hook from G:\Users\Adil\Documents\Projects\FCash\front-end\fcash-app\hooks\before-prepare\nativescript-dev-typescript.js
Executing before-prepare hook from G:\Users\Adil\Documents\Projects\FCash\front-end\fcash-app\hooks\before-prepare\nativescript-localize.js
Preparing project...
Project successfully prepared (Android)
Executing after-prepare hook from G:\Users\Adil\Documents\Projects\FCash\front-end\fcash-app\hooks\after-prepare\nativescript-dev-android-snapshot.js
Successfully transferred en.default.json.
Refreshing application...
Successfully synced application org.nativescript.Groceries on device 17a7d2ad.
Skipping prepare.
ActivityManager: Start proc 13664:org.nativescript.Groceries/u0a139 for activity org.nativescript.Groceries/com.tns.NativeScriptActivity
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
Successfully transferred strings.xml.
Refreshing application...
Successfully synced application org.nativescript.Groceries on device 17a7d2ad.**

**Comment by lfabreges** [comment]
Hi,

I noticed this problem too, I created the issue NativeScript/nativescript-cli#3251 as I think it is linked to the way nativescript-cli handles changes. A change should trigger a new build as application resources changes.

For now what you do is a good workaround.

Regards.

**Comment by lfabreges** [comment]
I'll keep this issue opened since this is still a problem
