### ISSUE TITLE
Trying to migrate from i18n plugin. Error Can't find variable: L

### ISSUE THREAD

**Issue by d3mac123** [lfabreges/nativescript-localize#16]
I am getting the error:
`file:///app/app.js:32:22: JS ERROR ReferenceError: Can't find variable: L`

while trying to print a localized string:
`console.log(L('wifiConnectivity'));`

I am using pure Javascript and I have the string set in the en.default.js file. Everything works when localizing the XML file but not working in the app.js file.

**Comment by spstratis** [comment]
I'm also migrating from i18n and am having this issue, my only difference is that I'm using Typescript. Does this plug-in not support the ability to localize strings in the JS/TS files?

**Comment by spstratis** [comment]
So I found a fix, although I would prefer a more global approach...

In the script file where you're trying to localize a string using `L('some_key')` you need to set `L` to the plugins localize object. EX:

**view-model.ts** 
```
let L = require("nativescript-localize").localize;

public load():void {
    console.log(L("some_key"));
}
```

**Comment by lfabreges** [comment]
Hi,

That is actually how it works, the plugin does not define a global L method, you have to import the localize method as shown by @spstratis, rename it if you want and use it directly. Same thing when developing with Typescript.

This plugin won't define a global method as it would pollute the global namespace, but that is something you can easily do by yourself if needed.

Regards.
