### ISSUE TITLE
Notification localization arguments fail on iOS due to strings files using %s instead of %@

### ISSUE THREAD

**Issue by spstratis** [lfabreges/nativescript-localize#20]
When sending a  localization key with localization arguments from APNS the localized arguments fail to display in the notification. This is due to the localizable strings file using %s instead %@ for formatting. 

If I open up the Project in Xcode, and replace the format tokens with %@, build and run, everything works fine. Is there a known work around for this?

Unfortunately, putting the correct token in the JSON files would cause issues in Android one everything builds.

**Comment by lfabreges** [comment]
What is the error encountered when building Android ?

**Comment by spstratis** [comment]
If you use the %@ as a formatting token in Android it causes the application to crash when a push notification is received. 

The error message is:
`java.util.unknownFormatConversionException: Conversion = '@'`

**Comment by lfabreges** [comment]
Thanks, I'll look into it

**Comment by lfabreges** [comment]
I just published v2.2.0, let me know if it works

**Comment by spstratis** [comment]
Looks like it's working great so far, thanks!
