### ISSUE TITLE
[angular] unable to resolve signature for pipe invocation

### ISSUE THREAD

**Issue by patrick-nurt** [lfabreges/nativescript-localize#23]
I keep getting this error in Visual Studio Code on the L pipe, any idea i how to solve it?

**Comment by domzinhuu** [comment]
For any reason if you create the html( or xml) file with my-page.component.android.html (for android) and my-page.component.ios.html(for ios) its work without errors in Vscode

**Comment by lfabreges** [comment]
Can you give me something to reproduce this behavior with the angular demo for example ? Are you using any Visual Studio Code specific plugin ?

**Comment by domzinhuu** [comment]
Its simples, install plugin, create a simple project with a component  and try use the L directive in a tag and you wil see the red line in vscode, but if you compile its works, only vscode show error.
![erro](https://user-images.githubusercontent.com/4142469/36236000-e171ce62-11da-11e8-9cba-ca02cce4aaf1.png)

**Comment by lfabreges** [comment]
I do not have intellisense or pipe resolution for angular template with my visual studio code installation, are you using a plugin ?

**Comment by domzinhuu** [comment]
yes i'm using many plugins for angular and nativescript

![captura de tela de 2018-02-16 16-53-08](https://user-images.githubusercontent.com/4142469/36323967-f6ff182e-1339-11e8-93b3-24edd2d3dadd.png)
![captura de tela de 2018-02-14 20-50-46](https://user-images.githubusercontent.com/4142469/36323974-ff968512-1339-11e8-97a1-43f1cfa2da04.png)

**Comment by yhyenifer** [comment]
me pasa igual y al pasarlo al celular no toma la tuberia

**Comment by Gio-Mgm** [comment]
I have the same issue with a date pipe, It works but underlined in red too (I am using webstorm)

`<span class="pull-right hidden-xs">{{ post.created_at | date: 'EEEE d MMMM y hh:mm a' }}</span>

![issue](https://user-images.githubusercontent.com/8613845/46239448-1a181a80-c399-11e8-93e4-b9299b3fb326.png)
`

**Comment by nukuuk** [comment]
Similar problem there using Luxon-Angular

**Comment by jlberrocal** [comment]
Same problem than @Gio-Mgm
