### ISSUE TITLE
Text including Fa icons

### ISSUE THREAD

**Issue by arcovoltaico** [lfabreges/nativescript-localize#27]
Hi,
I'm trying to translate the text of a button that is prefixed by a fa-icon.

[text]="'&#xf09a;' + ' login.fblogin' | L "  class="fa fb-button"

My json:
  "fblogin": "Login with Facebook", // not working

  "&#xf09a; fblogin": "&#xf09a; Login with Facebook", // detected but the fa-icon code is displayed as text as fa CSS seems to be executed before the i18n localize

And pasting the rendered icon:
 " fblogin": " Login with Facebook" // not working

Any idea?

Thanks a lot

**Comment by jorotenev** [comment]
This might be angular specific issue, because this works for me
```
<Button text="{{'&#xf230; ' + L('sign_in_with_fb') }}" class="btn btn-primary font-awesome"/>
```

**Comment by arcovoltaico** [comment]
Yes it's angular related. Meanwhile I found this workaround:

Component:
 //&#xf1e0; not working, had to use the icon:
    this.shareIt = " " + localize("requested.shareIt");

View:
 <Button class="fa"  [text]="shareIt" (tap)="share()"></Button>

**Comment by lfabreges** [comment]
Surrounded with parenthesis: `[text]="'' + ('login.fblogin' | L)" class="fa fb-button"` ?

**Comment by arcovoltaico** [comment]
Sorry, it's not working , just renders this :  login.fblogin

**Comment by lfabreges** [comment]
`<Label [text]="this_is_it + ('hello.world' | L)"></Label>` works for me where `this_is_it` is just a string, hello.world is correctly translated. Is `login.fblogin` a key in your i18n file ? you may want to double check that.

**Comment by lfabreges** [comment]
I'm closing this issue as this is not something I can fix with this plugin

**Comment by arcovoltaico** [comment]
It is , and translated fine from localize or alone in the view. The problem cames using two pipes and the parenthesis can avoid the need of using both :-(

**Comment by arcovoltaico** [comment]
I understand anyway the workaround would be helpful for others ;-)
