### ISSUE TITLE
How to localize coalesce texts

### ISSUE THREAD

**Issue by arcovoltaico** [lfabreges/nativescript-localize#28]
Hi,

This is only working for register (and should work for login too):
[text]="isLoggingIn ? 'login' : 'register' | L"

This will throw a template error:
[text]="isLoggingIn ? 'login' | L : 'register' | L"

**Comment by lfabreges** [comment]
Looks like an angular issue, have you tried `[text]="(isLoggingIn ? 'login' : 'register') | L"`

**Comment by arcovoltaico** [comment]
Unfortunately still giving template parsing error. For now, I'm duplicating the elements and using the coalesce in visibility attribute.

**Comment by lfabreges** [comment]
I'm closing this issue as this is not something I can fix with this plugin
