### ISSUE TITLE
Languages variations, pt-BR, es-AR, fr-CA

### ISSUE THREAD

**Issue by francisrod01** [lfabreges/nativescript-localize#34]
It is possible to determine a language variation?

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> /home/paneladm/projects/e-resto/tablet-v2-ns/platforms/android/app/src/main/res/values-es-ar: Error: Invalid resource directory name
```

## Environment ##

- "nativescript-angular": "~5.2.0",
- "nativescript-localize": "^3.0.2",

**Comment by lfabreges** [comment]
I just published a new release, let me know if it works. Thanks for the report.

**Comment by spstratis** [comment]
Will this only work if using newer versions TNS (above 3.4.1)?

**Comment by francisrod01** [comment]
Yeah, I'm using it now!

**Comment by spstratis** [comment]
I really need this fix but can't update to the newest version of Nativescript yet :(
