### ISSUE TITLE
The pipe 'L' could not be found

### ISSUE THREAD

**Issue by xjpmauricio** [lfabreges/nativescript-localize#39]
Hi, I'm getting this error:

```
JS: ERROR Error: Uncaught (in promise): Error: Template parse errors:
JS: The pipe 'L' could not be found
```

**Comment by Jameswr11** [comment]
Also getting this error

**Comment by xjpmauricio** [comment]
Hi @Jameswr11, please check this issue [here](https://github.com/NativeScript/nativescript-angular/issues/1403).

**Comment by goyote** [comment]
Also getting this error with the default instructions, why would this happen with just the default setup?
