### ISSUE TITLE
The pipe 'L' could not be found error

### ISSUE THREAD

**Issue by dvdbrk** [lfabreges/nativescript-localize#5]
Any ideas?

This actually used to work just fine week ago, but after removing the platform (android) and rebuilding the app - the error appears. Interesting enough, it does not report an error when parsing the json file - as the app title (app.name) works just fine.

**Comment by dvdbrk** [comment]
Sorted - if you are using lazy loading, even if you import the NativeScriptLocalizeModule in the Shared module - it would not work. Instead import the module in your lazy loaded module (not root, not shared, but the one loaded).

**Comment by lfabreges** [comment]
If importing the module in the shared module, you need to add it to the exports list as well, so that when you import the shared module, NativeScriptLocalizeModule comes with it.

**Comment by arcovoltaico** [comment]
Still having the issue if I my app.module is:

`import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptLocalizeModule } from "nativescript-localize/angular";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";

import { AppComponent } from "./app.component";

@NgModule({
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  imports: [
    NativeScriptModule,
    NativeScriptLocalizeModule
  ],
  schemas: [NO_ERRORS_SCHEMA],
})
export class AppModule {}`

**Comment by lfabreges** [comment]
Are you using the pipe in a lazy loaded module ?

**Comment by arcovoltaico** [comment]
Yes, my fault ,  I need to load the  NativeScriptLocalizeModule also on the page module...
