### ISSUE TITLE
How to get the current locale name in the angular component?

### ISSUE THREAD

**Issue by csi-stasik** [lfabreges/nativescript-localize#54]
Hi.

How to get the current locale name in the angular component like: en, de etc? 

For the moment as a workaround i placed on each translation file a key:

```
{"LOCALE":"en"} 
... 
```

```
{"LOCALE":"de"}  
...
```

which is translated in current language but should be a more intelligent way i think.

**Comment by lfabreges** [comment]
That's a great workaround. Otherwise you'll have to use native API to retrieve the current language.
