### ISSUE TITLE
Nativescript and Angular - problem with a modla

### ISSUE THREAD

**Issue by ivayloc** [lfabreges/nativescript-localize#56]
I am working on an app with lazy loading and I want to have localization functionality in a custom dialog window, I have placed the `NativeScriptLocalizeModule` in my featured module, the same module which my dialog is located in, but  when the dialog is opened there are placeholders instead of the texts `{{'translation.general.type_label' | L}}` -> `translation.general.type_label`

Angular 7.0
Nativescript 5.0.1
Nativescript localize 4.0.1

**Comment by ivayloc** [comment]
I saw the workaround with the change detection, but for some reason it's not working for me

**Comment by lfabreges** [comment]
Can you create a repo to reproduce this issue, I just played a little with modal and localization is working as expected ?

**Comment by ivayloc** [comment]
@lfabreges it is my mistake, I have missed the part with `...  make sure it contains the application name to avoid any error.`
