### ISSUE TITLE
Localize with Vue Js - Doesn't find key with special character

### ISSUE THREAD

**Issue by djokone** [lfabreges/nativescript-localize#57]
In my i18n en.default.json
{`
...
"settingTab.search.ageMin": "localize text",
...
}`

And when I use the localize filter
`<Label :text="'settingTab.search.ageMin'|L"/>`

It return settingTab.search.ageMin plain text
and it do the same when I try :
import { localize } from 'nativescript-localize'
{`
...
"settingTab_search_ageMin": "localize text",
...
}
console.log(localize("settingTab_search_ageMin"))
> return settingTab_search_ageMin
`

**Comment by lfabreges** [comment]
Hi, I'm not used to Vue, in your Label, I don't see the L pipe, did you try with it ?

Can you create a repo to reproduce the issue ?

**Comment by djokone** [comment]
Hi @lfabreges, thank you for your quick reply ! When I wanted to reproduce the issue in a repo, I've seen that it was working as expected. I think the problem was because of the cache that need to be reset to make it work. So every thing working now, thank you and sorry for the inconvenience :)
