### ISSUE TITLE
Do you have to add all string into the JSON file?

### ISSUE THREAD

**Issue by dvdbrk** [lfabreges/nativescript-localize#6]
So I am developing an app in both English and German. Default language is English, and the keywords I am translating are written in English, i.e. _{{ 'Log in' | L }}_

It looks like _"Log in"_ needs to exist in both en.json and de.json file? Is this really necessary, as it seems perfectly normal to, if the translation string is not found in en.json file, to show the keyword untranslated, as it is. All works fine for the German language, but is a huge overkill to have to add same keyword : translation pair to the en.json file as well?

**Comment by lfabreges** [comment]
The default behavior is to return the key if no translation exists for it. To determine if a translation exists for a key, the module relies on the OS native behavior.

What happens if you omit to translate a key in `en.json` ?

**Comment by dvdbrk** [comment]
Thank you for looking into this.

When I run the app, all elements / strings (not just the ones missing) to localize are empty (HTML is blank) and because the error is throws, no JS is executed at all. The issue is:

```
JS: EXCEPTION: Error in /data/data/org.nativescript.test/files/app/login.component.html:13:12 caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f06001e
JS:     android.content.res.Resources.getText(Resources.java:335)
JS:     android.content.res.Resources.getString(Resources.java:381)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
JS:     android.app.Fragment.performCreateView(Fragment.java:2353)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:816)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
JS:     android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6119)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
JS: ORIGINAL EXCEPTION: android.content.res.Resources$NotFoundException: String resource ID #0x7f06001e

```

**Comment by lfabreges** [comment]
Can you try with the new version 1.9.4 to see if it works. Delete `node_modules` and `platforms` directory if needed to ensure a fresh build.

**Comment by dvdbrk** [comment]
Thank you again for a quick patch. However, I cannot get it to work. So I have removed both `node_modules` and `platforms`, installed a plugin (1.9.4)... and after I have removed a few strings from en.default.json file (`app.name ` was left in), the issue throws is:

```
03-25 14:48:38.378 28121 28121 W System.err: org.json.JSONException: End of input at character 0 of
03-25 14:48:38.379 28121 28121 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
03-25 14:48:38.379 28121 28121 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:97)
03-25 14:48:38.379 28121 28121 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:156)
03-25 14:48:38.380 28121 28121 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:173)
03-25 14:48:38.380 28121 28121 W System.err:    at com.tns.FileSystem.readJSONFile(FileSystem.java:100)
```

Being a beginer in NS, I am not excluding the issue is in some other part of the code, but as soon as I return all strings back to JSON file, the error disappears.

**Comment by lfabreges** [comment]
That's weird, the file should be parsed only at build time by the before-prepare hook. Can you tell me when this error occurs and show me the content of your JSON file. Ideally if you could reproduce the error on a public repo so that I can investigate.
