### ISSUE TITLE
Does not localize

### ISSUE THREAD

**Issue by santteegt** [lfabreges/nativescript-localize#61]
Hi,

I'm trying to use your library on an app but the string is not being localized.

![image](https://user-images.githubusercontent.com/926341/50458424-faa97300-0930-11e9-94bf-6b25df834ca2.png)

I'm importing the `NativeScriptCommonModule ` on a shared module:

```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NativeScriptLocalizeModule } from "nativescript-localize/angular";

@NgModule({
 	imports: [ 
 		CommonModule,
 		NativeScriptLocalizeModule
	],
 	declarations: [
	],
	exports: [
	 	CommonModule,
	 	FormsModule,
	 	NativeScriptLocalizeModule
	]
})
export class SharedModule { }
```

Then on the component's module I'm importing this SharedModule:

```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptCommonModule } from "nativescript-angular/common";

import { LoginRoutingModule } from "./login-routing.module";
import { LoginComponent } from "./login.component";

import { SharedModule } from "../shared/shared.module";

@NgModule({
    imports: [
        NativeScriptCommonModule,
        LoginRoutingModule,
        SharedModule
    ],
    declarations: [
        LoginComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class LoginModule { }
```

And, on the component HTML template, I'm using the `L` pipe as follows:

```
...
<Label class="t-30 company-name" text="{{ 'app.name' | L }}"></Label>
...
```

My i18n directory structure is:

app
--i18n
----de.js
----en.default.js

The `en.default.js` contains:

```
module.exports = {
	"app.name": "My app",
	"company.name": "My company"
};
```

**Dependencies version**

* "@angular/core": "~7.0.0",
* "nativescript-angular": "~7.0.0",
* "nativescript-localize": "^4.1.0",

What could be the problem? Does the `app.name` should have the specific name for the nativescript app project I created?

**Comment by ibenzyk** [comment]
@santteegt I've faced same problem try to move you i18n folder one level up

src
--app
--i18n
----de.js
----en.default.js

and it works for me

**Comment by santteegt** [comment]
It worked! Thanks @ibenzyk

**Comment by vasudevpareek07** [comment]
@EddyVerbruggen, I am not able to change the language with in the app.


I created i18n directory under src folder, when i try to change the language, based on the documentation https://market.nativescript.org/plugins/nativescript-localize here for angular, 

Following things i imported in angular component:

import { android as _android } from '@nativescript/core/application';
import { overrideLocale } from 'nativescript-localize/localize';
import { isAndroid } from 'tns-core-modules/platform';

// function which i call when user tries to change the language

switchLanguage(selectedLang){
    L.localize.overrideLocale(selectedLang);
    if (isAndroid) {
        _android.foregroundActivity.finish();
    } 
}

Here it sasy 'L' is not defined. Any help would be appreciated. Thanks.
