### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by xlmnxp** [lfabreges/nativescript-localize#64]
when I try build my ios project I got "Path must be a string. Received undefined"
after called "before-checkForChanges/nativescript-localize.js"

**Comment by mennolp098** [comment]
Same here, trying to build for iOS gives error Path must be a string. Received undefined.

**Comment by thefallofbecause** [comment]
Happens for me too - both on Android & iOS in a NativeScript-Vue project.

I'm not even trying to use any functionality of the library yet, this happens just from adding
```
import { localize } from "nativescript-localize";
Vue.filter("L", localize);
```
to app.js

**Comment by lfabreges** [comment]
I updated demos to NS 5.2 and added a Vue.js demo and it works, can one of you give me the steps or a repo to reproduce the issue ?

**Comment by xlmnxp** [comment]
@lfabreges problem come when you build project to iOS

**Comment by lfabreges** [comment]
@xlmnxp I built the demos locally for iOS. Travis did too and it worked : https://travis-ci.org/lfabreges/nativescript-localize. I may be missing something but for now I'll need more info.

**Comment by lfabreges** [comment]
Could you try removing hooks, node_modules and platforms directories, running `npm i` and try again building your app for iOS ?

**Comment by xlmnxp** [comment]
@lfabreges I tried and same issue 
come from your plugin hook I don't know why :(

**Comment by mennolp098** [comment]
@lfabreges Just tried a clean project with the only exception to importing and adding localize as filter. It still gives me the error of path undefined.

Steps I did:
NS-Sidekick -> new project -> Nativescript-Vue blank project -> add plugin -> Nativescript-Localize -> Import localize method into app.js -> Add Vue filter into app.js -> build app for iOS.

**Comment by xlmnxp** [comment]
@mennolp098 I tried nativescript-i18n and it's work fine after last update

**Comment by lfabreges** [comment]
@mennolp098 Here's what I tried:

NS Sidekick
New NS Vue Blank project
Added nativescript-localize plugin
import localize and add filter into app.js
Build app for iOS

It worked, I tried a local build and a cloud build. I then added an i18n folder with an en.default.json file in it and it worked too.

I'm using MacOSX, NS version 5.2.

What are you using ? Are there any steps that you did not mention in your post (even small steps) ?

Thx.

**Comment by xlmnxp** [comment]
@lfabreges I'm using NativeScript SideKick with clean build

**Comment by mennolp098** [comment]
@lfabreges Seems like you did the exact same steps as I did. The only difference between us is that I am using Node v8.8.1

**Comment by lfabreges** [comment]
Found the bug, tough one, it should work now using 4.1.1
