### ISSUE TITLE
[Question] add localization data at runtime

### ISSUE THREAD

**Issue by aaayushsingh** [lfabreges/nativescript-localize#65]
Is there a way to add/update localization data at run time? 

Let's say I have an api that periodically gets new content that needs to be localized. How can I update the data in app accordingly? 

Will it work if I just overwrite the json files in the folders?

**Comment by lfabreges** [comment]
No, that's not possible, at least not with this plugin as it uses iOS and Android native API. The JSON files are actually useless at runtime, they're just used at compile time by the before-checkForChanges hook to build the localization files for Android and iOS.
