### ISSUE TITLE
Multi-substitution fails on Android

### ISSUE THREAD

**Issue by agisboye** [lfabreges/nativescript-localize#7]
Strings with multiple substitutions, i.e. "Hello %s, how is your %s?", fail on Android with the following error:

> Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?

Android expects the substitutions to be numbered. Adding `formatted="false"` before the name attribute on the <string> tag [here](https://github.com/lfabreges/nativescript-localize/blob/master/hooks/before-prepare.android.ts#L47) seems to resolve the issue, but I'm not sure if it has other consequences.

**Comment by lfabreges** [comment]
Thank you, I've patched the plugin, it should work. You may need to delete the platforms directory to ensure a fresh build.
